---
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build -t ghcr.io/tiyaskar/video_call:latest
  push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - run:
          name: Push Image to github
          command: docker push ghcr.io/tiyaskar/video_call:latest


workflows:
  build-deploys:
    jobs:
      - build
      - push:
          require:
            - build
  triggers:
    - event: push
      branch: master