---
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Build Image
          command: docker build -t ghcr.io/tiyaskar/video_call:latest .
  push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Push Image to github
          command: docker push ghcr.io/tiyaskar/video_call:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - push:
          requires:
            - build

triggers:
  - event: push
    branch: master