name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  pull_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node environment:Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Test dependencies
        run: npm ci
  
  build_and_push:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [ pull_and_test ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${GITHUB_REF##*/} .
        if: success()

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      
      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}
        if: success()
  
  scan_docker_image:
    runs-on: ubuntu-latest
    needs: [ build_and_push ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Scan Docker image
        uses: snyk/actions/docker@master
        continue-on-error: true
        with:
          image: ghcr.io/tiyaskar/video_call:master
          args: --file=Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk report as sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      
